export const ActionReducer = {
    SET_PRELOAD: "SET_PRELOAD",

    SET_AUTH: "SET_AUTH",
    UNSET_AUTH: "UNSET_AUTH",
    UPDATE_PROFILE_USER: "UPDATE_PROFILE_USER",

    SET_LOADING: "SET_LOADING",

    SET_HOME_REFRESH: "SET_HOME_REFRESH",

    SET_CATEGORIES_SPEND: "SET_CATEGORIES_SPEND",
    ADD_CATEGORIES_SPEND: "ADD_CATEGORIES_SPEND",
    DELETE_CATEGORY_SPEND: "DELETE_CATEGORY_SPEND",
    UPDATE_CATEGORY_SPEND: "UPDATE_CATEGORY_SPEND",

    SET_SUM_TRANSACTION_BY_CATEGORY: "SET_SUM_TRANSACTION_BY_CATEGORY",
    ADD_SUM_TRANSACTION_BY_CATEGORY: "ADD_SUM_TRANSACTION_BY_CATEGORY",
};

export enum ActionReducerType  {
    SET_PRELOAD = "SET_PRELOAD",

    SET_AUTH = "SET_AUTH",
    UNSET_AUTH = "UNSET_AUTH",
    UPDATE_PROFILE_USER = "UPDATE_PROFILE_USER",

    SET_LOADING = "SET_LOADING",

    SET_HOME_REFRESH = "SET_HOME_REFRESH",

    SET_CATEGORIES_SPEND = "SET_CATEGORIES_SPEND",
    ADD_CATEGORIES_SPEND = "ADD_CATEGORIES_SPEND",
    DELETE_CATEGORY_SPEND = "DELETE_CATEGORY_SPEND",
    UPDATE_CATEGORY_SPEND = "UPDATE_CATEGORY_SPEND",

    SET_SUM_TRANSACTION_BY_CATEGORY = "SET_SUM_TRANSACTION_BY_CATEGORY",
    ADD_SUM_TRANSACTION_BY_CATEGORY = "ADD_SUM_TRANSACTION_BY_CATEGORY"
}
